/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/hutiaoxia.glb");
  return (
    <group ref={group} {...props}>
      <mesh
        material={materials.ray_surface}
        geometry={nodes.hutiaoxia.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.1, 0.1, 0.1]}
      />
    </group>
  );
}

useGLTF.preload("/hutiaoxia.glb");
